"""Custom Pipecat frames for the active-coach pipeline (ADR-013).

``CoachActionFrame`` carries one ``CoachAction`` from the structured LLM
processor downstream to the ``ActionDispatcherProcessor``. It is a ``DataFrame``
so it is cancelled by user interruptions like a normal TextFrame would be.

``SafetyResponseFrame`` is emitted by ``SafetyGuardProcessor`` instead of a
plain ``TextFrame`` so downstream pieces (e.g. transcripts) can tell a
LLM-bypass safety reply apart from a normal coach turn.
"""

from __future__ import annotations

from dataclasses import dataclass

from pipecat.frames.frames import DataFrame, TextFrame

from app.core.coach_response import CoachAction
from app.core.safety import DangerLevel


@dataclass
class CoachActionFrame(DataFrame):
    """One structured action emitted by the coach LLM."""

    action: CoachAction | None = None  # default needed: DataFrame dataclass forbids required fields

    def __str__(self) -> str:
        a = self.action
        return f"{self.name}(action={type(a).__name__ if a else 'None'})"


@dataclass
class SafetyResponseFrame(TextFrame):
    """A coach response generated by SafetyGuardProcessor (LLM bypassed)."""

    level: DangerLevel | None = None
